### ISSUE TITLE
Create draft for web ui

### ISSUE THREAD

**Issue by deinhofer** [asterics/asterics-web#2]
* Create draft for web ui
![image](https://user-images.githubusercontent.com/13609768/42284178-000ac06a-7fac-11e8-8b96-321cca1f04f2.png)

See current wireframe draft: https://github.com/asterics/asterics-web/blob/master/specification/wireframes/pencil-test.epgz

**Comment by deinhofer** [comment]
# Variant with reduced main categories

![image](https://user-images.githubusercontent.com/13609768/42510579-9eb279c2-844f-11e8-8ea4-9c99d9adb170.png)

**Comment by sabicalija** [comment]
First draft implementation (incl. vue-router and responsive navigation) available [here](https://github.com/asterics/asterics-web/commit/d010628db561b37905d1e1c9fafee7541d605491). 

![image](https://user-images.githubusercontent.com/13609768/42979999-88dc87f4-8bd5-11e8-8273-fcf7ff182568.png)

**Comment by deinhofer** [comment]
Done https://github.com/asterics/asterics-web/tree/sprint-201808-vuetify
